import { useState } from 'react';
import { Badge } from '@components/ui/badge';
import { Dialog, DialogContent } from '@components/ui/dialog';
import { TrendingUp, TrendingDown, Minus, Sparkles, X, Brain, Calendar, Activity } from 'lucide-react';
import { Button } from '@components/ui/button';

interface SignalBadgeProps {
  signal: 'positive' | 'neutral' | 'negative';
  rationale?: string | null;
  className?: string;
}

/**
 * Displays a clickable deal signal badge that reveals AI rationale when clicked
 */
export default function SignalBadge({ signal, rationale, className = '' }: SignalBadgeProps) {
  const [showModal, setShowModal] = useState(false);

  const signalConfig = {
    positive: {
      icon: TrendingUp,
      label: 'Positive',
      emoji: '🟢',
      badgeClass: 'bg-gradient-to-br from-green-100 to-emerald-100 text-green-700 border-green-300 hover:from-green-200 hover:to-emerald-200 cursor-pointer transition-all shadow-sm',
      rationaleClass: 'bg-green-50 border-green-200 text-green-900',
    },
    neutral: {
      icon: Minus,
      label: 'Neutral',
      emoji: '🟡',
      badgeClass: 'bg-gradient-to-br from-amber-100 to-yellow-100 text-amber-700 border-amber-300 hover:from-amber-200 hover:to-yellow-200 cursor-pointer transition-all shadow-sm',
      rationaleClass: 'bg-amber-50 border-amber-200 text-amber-900',
    },
    negative: {
      icon: TrendingDown,
      label: 'Negative',
      emoji: '🔴',
      badgeClass: 'bg-gradient-to-br from-red-100 to-rose-100 text-red-700 border-red-300 hover:from-red-200 hover:to-rose-200 cursor-pointer transition-all shadow-sm',
      rationaleClass: 'bg-red-50 border-red-200 text-red-900',
    },
  };

  const config = signalConfig[signal];
  const Icon = config.icon;

  const handleClick = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (rationale) {
      setShowModal(true);
    }
  };

  return (
    <>
      <div className={`relative ${className}`}>
        <Badge
          variant="outline"
          className={`${config.badgeClass} ${rationale ? 'cursor-pointer' : 'cursor-default'}`}
          onClick={handleClick}
          title={rationale ? 'Click to see detailed AI analysis' : 'No analysis available yet'}
        >
          <Icon className="w-3 h-3 mr-1" />
          {config.label}
          {rationale && <Sparkles className="w-3 h-3 ml-1 opacity-60" />}
        </Badge>
      </div>

      {/* AI Analysis Modal */}
      <Dialog open={showModal} onOpenChange={setShowModal}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          {/* Header */}
          <div className="flex items-start justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className={`p-3 rounded-xl ${config.badgeClass}`}>
                <Brain className="w-6 h-6" />
              </div>
              <div>
                <h2 className="text-2xl font-bold text-slate-900">AI Signal Analysis</h2>
                <p className="text-sm text-slate-500 mt-1">Comprehensive deal health assessment</p>
              </div>
            </div>
          </div>

          {/* Signal Status */}
          <div className={`p-6 rounded-xl border-2 ${config.rationaleClass} mb-6`}>
            <div className="flex items-center gap-3 mb-3">
              <Icon className="w-5 h-5" />
              <h3 className="text-lg font-semibold">Current Signal: {config.label}</h3>
            </div>
            <div className="flex items-center gap-2 text-sm opacity-75">
              <Calendar className="w-4 h-4" />
              <span>Last analyzed: {new Date().toLocaleDateString()}</span>
            </div>
          </div>

          {/* Detailed Rationale */}
          <div className="space-y-4">
            <div className="flex items-center gap-2 mb-3">
              <Activity className="w-5 h-5 text-purple-600" />
              <h3 className="text-lg font-semibold text-slate-900">Analysis Details</h3>
            </div>
            
            <div className="bg-slate-50 border border-slate-200 rounded-lg p-6">
              <p className="text-slate-700 leading-relaxed whitespace-pre-wrap">
                {rationale || 'No detailed analysis available yet.'}
              </p>
            </div>

            {/* AI Disclaimer */}
            <div className="flex items-start gap-2 p-4 bg-purple-50 border border-purple-200 rounded-lg">
              <Sparkles className="w-4 h-4 text-purple-600 mt-0.5 flex-shrink-0" />
              <p className="text-xs text-purple-800">
                This analysis is generated by AI based on deal activities, timeline, and engagement patterns. 
                Signal updates automatically when new activities are logged.
              </p>
            </div>
          </div>

          {/* Close Button */}
          <div className="flex justify-end mt-6 pt-4 border-t border-slate-200">
            <Button
              onClick={() => setShowModal(false)}
              variant="outline"
              className="px-6"
            >
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
